spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///crm
    username: root
    password: tiger
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #这句是扫描mapper.xml文件的！同样在mapper.java中加上了@mapper来扫描mapper.java文件

